#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct agent
{
    vec2 position;
    float angle;
    float padding;
};

layout(push_constant) uniform PushConstants {
    int numAgents;
    float moveSpeed;
    float diffuseSpeed;
    float evaporateSpeed;
    float turnSpeed;
    float deltaTime;
} constants;

layout(set = 0, binding = 0, std430) buffer AgentData
{
    agent agents[];
} agentData;

layout(set = 0, binding = 1, rgba8) uniform image2D image;

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id >= constants.numAgents) return;

    // set new position and draw path on map
    vec4 newColor = vec4(1.0, 1.0, 1.0, 1.0);
    imageStore(image, ivec2(agentData.agents[id].position), newColor);
}